application/charts/urls.py
from django.conf.urls import url
from . import views

app_name = 'charts'
urlpatterns = [
    # url(r'^sensor-data-table/', views.SensorDataListPeginate.as_view(), name='sensor_table'),
    url(r'^sensor-data-chart/by-item/', views.ChartsByItemView.as_view(), name='sensor_chart_by_item'),
    # url(r'^sensor-data-chart/by-sensor/', views.ChartsBySensorView.as_view(), name='sensor_chart_by_sensor'),
]

meza_vis/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
    url(r'^api/', include('application.api.urls')),
    url(r'^charts/', include('application.charts.urls')),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

application/charts/models.py
from django.db import models

# Create your models here.

application/charts/views.py
from application.api.models import SensorData

from django.views import generic

# class ChartsByItemView(LoginRequiredMixin, generic.TemplateView):
class ChartsByItemView(generic.TemplateView):
    template_name = "charts/charts_by_item.html"

    # chart用のデータはhtmlから直接取得手続きを取る(RESTapi経由で取得)からcontextに渡す必要はない
    # テンプレートに自分が定義したデータを渡したい
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # はじめに継承元のメソッドを呼び出す
        context["template_iteration"] = range(3)  # テンプレートでforループするときに使う
        return context

application/charts/templates/charts/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    {% load static %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- CSS -->
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <!-- MetisMenu CSS android向けのやつ-->
    <link href="{% static 'bootstrap/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom CSS -->
    <link href="{% static 'bootstrap/dist/css/sb-admin-2.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'bootstrap/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- 自分で設定したcssを追加で読み込ませている -->
    <link href="{% static 'charts/css/structure.css' %}" rel="stylesheet" type="text/css">


    {% block head %}
    {% endblock %}


</head>

<body>


    <div id="wrapper">
        <!-- Navigationバー -->
        <nav class="navbar navbar-default navbar-static-top manager-nav no-margin" role="navigation">
            <!-- Navigationバーの上部に表示されるヘッダー-->
            <div class="navbar-header">
                <a class="navbar-brand"> ダッシュボード </a>
            </div>

            <!-- Navigationバーの右側に表示されるリンク-->
            <ul class="nav navbar-top-links navbar-right">
                <!-- ドロップダウン -->
                <li class="dropdown">

                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>

                    <ul class="dropdown-menu dropdown-user">
{#                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>#}
{#                        </li>#}
{#                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>#}
{#                        </li>#}
                        <li class="divider"></li><!-- 区切り線 -->
{#                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>#}
{#                        <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>#}
                        </li>
                    </ul>

                </li>
            </ul>

            <!-- サイドバーの表示関係 -->
            <div class="navbar-default sidebar" role="navigation">
              <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">

                    <!-- チャートへのリンク-->
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'charts:sensor_chart_by_item' %}">項目別</a>
                            </li>
{#                            <li>#}
{#                                <a href="{% url 'charts:sensor_chart_by_sensor' %}">センサー別</a>#}
{#                            </li>#}
                        </ul>
                    </li>

                    <!-- テーブルへのリンク -->
{#                    <li>#}
{#                        <a href="{% url 'charts:sensor_table' %}"><i class="fa fa-table fa-fw"></i> Tables </a>#}
{#                    </li>#}

                </ul>
              </div>
            </div>

        </nav>
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

application/charts/templates/charts/charts_by_item.html
{% extends "charts/base.html" %}

{% load static %}

{% block title %}Sensor Data Chart{% endblock %}

{% block head %}
    <!--javascript-->
    <!-- jQuery -->
    <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'bootstrap/vendor/metisMenu/metisMenu.min.js' %}"></script>
    <!-- 「SB admin2」のチャート関係 -->
    <!-- Flot Charts JavaScript -->
    <!---->
    <script src="{% static 'bootstrap/vendor/flot/excanvas.min.js' %}"></script>
    <!--  チャート描画  -->
    <script src="{% static 'bootstrap/vendor/flot/jquery.flot.js' %}"></script>
    <!--  チャートをブラウザの大きさに合わせてリサイズ jquery.flot.js　の後に呼び出すこと -->
    <script src="{% static 'bootstrap/vendor/flot/jquery.flot.resize.js' %}"></script>
    <!---->
    <script src="{% static 'bootstrap/vendor/flot-tooltip/jquery.flot.tooltip.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'bootstrap/dist/js/sb-admin-2.js' %}"></script>

    <!--high chart-->
    <!--<script type="text/javascript" src='http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js';></script>-->
    <script src="http://code.highcharts.com/highcharts.js";></script>

    <!-- ajax csrf 対策 -->
    <script src="{% static 'api/set_csrf_ajax_on_django.js' %}"></script>

    {#  datepicker用 #}
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/redmond/jquery-ui.css" >
    <script>

        // datepickerに関する記述
        //今日の日付データ
        var date_now=new Date();
        var year = date_now.getFullYear();
        var month = date_now.getMonth()+1;
        var day = date_now.getDate();
        var date_now_str = year + "/" + month + "/" +day

        $(function(){
            // $('#datepicker').datepicker();
            // datapickerのイベントを受けて特定の関数を実行
            $('#datepicker').datepicker({
                onSelect: function(dateText){
                    //alert(dateText);
                    drawDesignateDate($('#datepicker').val());
                },
            });
            // 初期値に今日の日付を設定
            //$("#datepicker").datepicker("setDate", date_now_str);
            $("#datepicker").datepicker("setDate", new Date());
            // ボタンを配置
            $("#datepicker").datepicker("option", "showOn", 'button');

        });


    </script>




{% endblock %}

{% block body %}
<div id="wrapper">
    <div id="page-wrapper">
        <!-- 項目表示部分 -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"> Charts For Each Item </h1>
            </div>
            <div>
                <p>
                    <input type="text" id="datepicker">
                </p>
            </div>
        </div>
{#        <!-- データテーブル表示用パネル -->#}
{#        <div class="row">#}
{#            <div class="col-lg-12">#}
{#                <div class="panel panel-default">#}
{#                    <!-- パネルのヘッダー -->#}
{#                    <div class="panel-heading">#}
{#                        Line Chart Example#}
{#                    </div>#}
{#                    <!-- /.panel-heading -->#}
{#                    <!-- パネルの表示内容（テーブル） -->#}
{#                    <div class="panel-body">#}
{#                        <div class="flot-chart">#}
{#                            <div class="flot-chart-content" id="flot-line-chart"></div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <!-- /.panel-body -->#}
{#                </div>#}
{#                <!-- /.panel -->#}
{#            </div>#}
{#        </div>#}



        <!-- チャート表示用パネルを作っておく -->
        {% for i in template_iteration %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <!-- パネルのヘッダー -->
                        <div class="panel-heading">
                            chart-{{ forloop.counter }}
                        </div>
                        <!-- /.panel-heading -->
                        <!-- パネルの表示内容（テーブル） -->
                        <div class="panel-body">
{#                            <div>#}
{#                                <input type="text" id="datepicker">#}
{#                            </div>#}
                            <div>
                                <!--   ここにhighChartが表示される-->
                                <div id='container-{{ forloop.counter }}'></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
        {% endfor %}


    </div>
</div>




<script type="text/javascript">

    function drawDesignateDate(designate_date){
        // HighChartに渡すための描画設定情報を先に生成しておく
        // 温度グラフ描画の設定
        var options_temp = {
            // チャートの設定
            chart :{
                renderTo : "container-1",// 出力先を指定
                //type : "column",// チャートの種類
             },

            // HighChartホームページへのリンク先の表示を消す
            credits: {
                enabled: false
            },

            // タイトルを指定
            title : {text: "温度データ"},

            // x軸のラベルを指定
            xAxis : {
                type: 'datetime',// x軸を時間軸に設定
                title: {text: "時間"},
            },

            // y軸のラベルを指定
            yAxis : {
                title: {text: "温度"},
            },
        }
        // 湿度グラフ描画の設定
        var options_humid = {
            // チャートの設定
            chart :{
                renderTo : "container-2",// 出力先を指定
                //type : "column",// チャートの種類
            },

            // HighChartホームページへのリンク先の表示を消す
            credits: {
                enabled: false
            },

            // タイトルを指定
            title : {text: "湿度データ"},

            // x軸のラベルを指定
            xAxis : {
                type: 'datetime',// x軸を時間軸に設定
                title: {text: "時間"},
            },

            // y軸のラベルを指定
            yAxis : {
                title: {text: "湿度"},
            },
        }
        var options_atmo = {
            // チャートの設定
            chart :{
                renderTo : "container-3",// 出力先を指定
                //type : "column",// チャートの種類
            },

            // HighChartホームページへのリンク先の表示を消す
            credits: {
                enabled: false
            },

            // タイトルを指定
            title : {text: "気圧データ"},

            // x軸のラベルを指定
            xAxis : {
                type: 'datetime',// x軸を時間軸に設定
                title: {text: "時間"},
            },

            // y軸のラベルを指定
            yAxis : {
                title: {text: "気圧"},
            },
        }


        // この後、options['series']に実際のデータを格納すれば、グラフ描画のソースとして利用できる
        // 今回はajaxのPOSTを利用して、DjangoのREST_APIからデータを得ることにする。
        // Djangoのでajaxからpostする場合、通常の方法ではCSRFTokenが得られず403エラーとなる。
        // これを回避するために、head部にCSRFをajaxにsetするための「$.ajaxSetup」を記述している
        // ちなみにGETであればcsrfなしでもajaxで処理できる

        // この後実行するajax(POST)時のエラー処理内容を事前に書いておく
        var handleError = function (error_data) {
            console.log("error");
            console.log(error_data);
        }

        // この後実行するajax(POST)時の処理内容を事前に書いておく
        var handleSuccess = function(data){
            var temps = [];
            var humids = [];
            var atmos = [];

            //console.log(data);
            // センサーのモデル名毎にデータをまとめたいので
            // keyからモデル名（各センサーに与えられた名前）を得ている
            var model_keys= Object.keys(data);
            //console.log(model_keys);

            // この辺はhighchartへのデータの渡し方を参すること
            // options['series'}に格納していけばよいと思う
            options_temp['series'] = [];
            options_humid['series'] = [];
            options_atmo['series'] = [];
            for(var i = 0; i < model_keys.length; i++){
                temps = data[model_keys[i]].temps;
                humids = data[model_keys[i]].humids;
                atmos = data[model_keys[i]].atmos;

                var series_temp ={
                    name: model_keys[i],
                    data: temps
                }
                var series_humid ={
                    name: model_keys[i],
                    data: humids
                }
                var series_atmo ={
                    name: model_keys[i],
                    data: atmos
                }
                options_temp['series'].push(series_temp);
                options_humid['series'].push(series_humid);
                options_atmo['series'].push(series_atmo);
            }

            //チャートの設定や表示データが格納された入れ物を渡してチャートを作る
            new Highcharts.Chart(options_temp);
            new Highcharts.Chart(options_humid);
            new Highcharts.Chart(options_atmo);

        }

        // ajaxによるPOST処理
        //var endpoint = '/api/chart/'
        var endpoint = '/api/chart/' + designate_date;

        $.ajax({
            method: "GET",
            url: endpoint,
            dataType: 'json',
            contentType: 'application/json',
{#            data: JSON.stringify(#}
{#                    // POSTする内容#}
{#                    {designatedate: designate_date}#}
{#            ),#}
            success: handleSuccess,
            error: handleError
        });

    }

    //jQuery:HTML=DOMの読み込みが終わったらfunction()の中の処理(=なにかしらの処理)を実行するという意味
    // $(function(){…}) と同じ意味
    $(function(){
        drawDesignateDate($('#datepicker').val());
    })


</script>

{% endblock %}